// +build autogen

// Package dockerversion is auto-generated at build-time
package dockerversion

// Default build-time variable for library-import.
// This file is overridden on build with build-time informations.
const (
	GitCommit          string = "dca76ed-unsupported"
	Version            string = "1.14.0-dev"
	BuildTime          string = "2017-02-21T07:43:39.831266159+00:00"
	IAmStatic          string = "true"
)

// AUTOGENERATED FILE; see /go/src/github.com/docker/docker/hack/make/.go-autogen
